version: '3'
services:
  datapipeline:
    image: mozilla/sbt
    container_name: datapipeline
    volumes:
      - ./src:/home/src
      - ./project:/home/project
      - ./build.sbt:/home/build.sbt
      - ~/.ivy2:/root/.ivy2
    entrypoint: bash -c "cd home && sbt run"
    networks:
      - dbpipeline

  postgresdb:
    image: postgres:11.4
    container_name: postgresdb
    ports:
      - 5432:5432
    networks:
      - dbpipeline
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

networks:
  dbpipeline: