version: '3'
services:
  postgresdb:
    image: postgres:11.4
    container_name: postgresdb
    ports:
      - 5432:5432
    networks:
      - dbpipeline
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  datagen:
    build:
      context: ./data
    container_name: datagen
    depends_on:
      - postgresdb
    volumes:
      - ./data:/home
    networks:
      - dbpipeline
    environment:
      - GEN_ROWS=1000
      - PG_HOST=postgresdb
      - PG_USER=postgres
      - PG_DATABASE=postgres
      - PGPASSWORD=mysecretpassword

networks:
  dbpipeline: